#!/usr/bin/env bash
# ============================================================================
# tron-grid-dots — theme generator.
#
# Reads theme/palette.sh (honoring $ACCENT) and produces every per-app color
# file. Two mechanisms:
#
#   1. GENERATED INCLUDES (*.gen.*): written INTO the repo config tree and
#      picked up through the symlinks. Gitignored, so the repo stays clean
#      whichever accent you use. Used by apps that support include files:
#      kitty, polybar, rofi, eww (scss), dunst (dunstrc.d), tmux, fish.
#
#   2. RENDERED COPIES: apps with no include mechanism (starship, fastfetch,
#      btop, openbox theme) get the committed cyan-default file copied to its
#      real location with the accent hexes swapped in place.
#
# Idempotent; safe to re-run any time. Run directly or via install.sh.
# ============================================================================
set -u

THEME_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
REPO_DIR="$(dirname "$THEME_DIR")"
CONF="$REPO_DIR/config"
XDG="${XDG_CONFIG_HOME:-$HOME/.config}"

# shellcheck source=palette.sh
. "$THEME_DIR/palette.sh"

say() { printf '\033[36m[theme]\033[0m %s\n' "$*"; }

# Persist the accent choice so palette.sh resolves it in future sessions
mkdir -p "$XDG"
printf '%s\n' "$ACCENT" > "$XDG/tron-accent"
say "accent = $ACCENT (primary $TRON_ACCENT, alt $TRON_ACCENT_ALT)"

# render_swapped SRC DST — copy SRC to DST; in orange mode swap the cyan and
# orange hexes (and the fastfetch-style decimal RGB triplets) symmetrically.
render_swapped() {
    local src="$1" dst="$2"
    mkdir -p "$(dirname "$dst")"
    if [ "$ACCENT" = "orange" ]; then
        sed -e 's/#00E5FF/@@A@@/g;   s/#FF4A1C/#00E5FF/g; s/@@A@@/#FF4A1C/g' \
            -e 's/#6FC3DF/@@B@@/g;   s/#FF8A5C/#6FC3DF/g; s/@@B@@/#FF8A5C/g' \
            -e 's/0;229;255/@@C@@/g; s/255;74;28/0;229;255/g; s/@@C@@/255;74;28/g' \
            "$src" > "$dst"
    else
        cp "$src" "$dst"
    fi
}

# ---------------------------------------------------------------- kitty ----
cat > "$CONF/kitty/colors.gen.conf" <<EOF
# GENERATED by theme/apply.sh — do not edit (edit theme/palette.sh instead)
foreground            $TRON_FG
background            $TRON_BG
selection_foreground  $TRON_BG
selection_background  $TRON_ACCENT
cursor                $TRON_ACCENT
cursor_text_color     $TRON_BG
url_color             $TRON_ACCENT_SOFT
active_border_color   $TRON_ACCENT
inactive_border_color $TRON_FG_DIM
active_tab_foreground   $TRON_BG
active_tab_background   $TRON_ACCENT
inactive_tab_foreground $TRON_FG_DIM
inactive_tab_background $TRON_BG_ALT

# terminal palette (tron-tinted)
color0  $TRON_BG_ALT
color8  $TRON_FG_DIM
color1  $TRON_ORANGE
color9  $TRON_ORANGE_SOFT
color2  #3DDC97
color10 #5CEBB0
color3  #FFC857
color11 #FFD98A
color4  $TRON_CYAN_SOFT
color12 #8FD8F0
color5  #9B7EDE
color13 #B79CF0
color6  $TRON_CYAN
color14 #66EFFF
color7  $TRON_FG
color15 #E8F2F8
EOF
say "kitty  -> config/kitty/colors.gen.conf"

# -------------------------------------------------------------- polybar ----
cat > "$CONF/polybar/colors.gen.ini" <<EOF
; GENERATED by theme/apply.sh — do not edit (edit theme/palette.sh instead)
[colors]
bg        = $TRON_BG
bg-alt    = $TRON_BG_ALT
fg        = $TRON_FG
fg-dim    = $TRON_FG_DIM
accent    = $TRON_ACCENT
accent-soft = $TRON_ACCENT_SOFT
alt       = $TRON_ACCENT_ALT
warn      = $TRON_WARN
ok        = $TRON_OK
EOF
say "polybar -> config/polybar/colors.gen.ini"

# ----------------------------------------------------------------- rofi ----
cat > "$CONF/rofi/colors.gen.rasi" <<EOF
/* GENERATED by theme/apply.sh — do not edit (edit theme/palette.sh instead) */
* {
    tron-bg:        ${TRON_BG}F2;   /* ~95% opaque */
    tron-bg-alt:    $TRON_BG_ALT;
    tron-fg:        $TRON_FG;
    tron-fg-dim:    $TRON_FG_DIM;
    tron-accent:    $TRON_ACCENT;
    tron-accent-soft: $TRON_ACCENT_SOFT;
    tron-warn:      $TRON_WARN;
}
EOF
say "rofi   -> config/rofi/colors.gen.rasi"

# ------------------------------------------------------------------ eww ----
rm -f "$CONF/eww/_colors.gen.scss"   # pre-rename leftover
# Keep _generated.scss for anything that still imports it, but the HUD reads
# the inlined PALETTE block in eww.scss (eww compiles from a temp cwd).
cat > "$CONF/eww/_generated.scss" <<EOF
// GENERATED by theme/apply.sh — do not edit (edit theme/palette.sh instead)
\$bg:          $TRON_BG;
\$bg-alt:      $TRON_BG_ALT;
\$fg:          $TRON_FG;
\$fg-dim:      $TRON_FG_DIM;
\$accent:      $TRON_ACCENT;
\$accent-soft: $TRON_ACCENT_SOFT;
\$alt:         $TRON_ACCENT_ALT;
\$warn:        $TRON_WARN;
\$ok:          $TRON_OK;
EOF
# Rewrite the inlined block in eww.scss so orange/cyan actually apply.
eww_scss="$CONF/eww/eww.scss"
if [ -f "$eww_scss" ]; then
    eww_tmp="$(mktemp)"
    awk -v pbegin="// === PALETTE BEGIN ===" -v pend="// === PALETTE END ===" \
        -v bg="$TRON_BG" -v bga="$TRON_BG_ALT" -v fg="$TRON_FG" -v fgd="$TRON_FG_DIM" \
        -v ac="$TRON_ACCENT" -v acs="$TRON_ACCENT_SOFT" -v alt="$TRON_ACCENT_ALT" \
        -v warn="$TRON_WARN" -v ok="$TRON_OK" '
        $0 == pbegin {
            print
            print "$bg:          " bg ";"
            print "$bg-alt:      " bga ";"
            print "$fg:          " fg ";"
            print "$fg-dim:      " fgd ";"
            print "$accent:      " ac ";"
            print "$accent-soft: " acs ";"
            print "$alt:         " alt ";"
            print "$warn:        " warn ";"
            print "$ok:          " ok ";"
            skip=1
            next
        }
        $0 == pend { skip=0 }
        skip { next }
        { print }
    ' "$eww_scss" > "$eww_tmp" && mv "$eww_tmp" "$eww_scss"
fi
say "eww    -> config/eww/eww.scss palette + _generated.scss"

# ---------------------------------------------------------------- dunst ----
mkdir -p "$CONF/dunst/dunstrc.d"
cat > "$CONF/dunst/dunstrc.d/50-colors.gen.conf" <<EOF
# GENERATED by theme/apply.sh — do not edit (edit theme/palette.sh instead)
[global]
    frame_color = "$TRON_ACCENT"
    separator_color = "$TRON_FG_DIM"

[urgency_low]
    background = "$TRON_BG"
    foreground = "$TRON_FG_DIM"
    frame_color = "$TRON_FG_DIM"

[urgency_normal]
    background = "$TRON_BG"
    foreground = "$TRON_FG"
    frame_color = "$TRON_ACCENT"

[urgency_critical]
    background = "$TRON_BG"
    foreground = "$TRON_FG"
    frame_color = "$TRON_WARN"
    timeout = 0
EOF
say "dunst  -> config/dunst/dunstrc.d/50-colors.gen.conf"

# ----------------------------------------------------------------- tmux ----
cat > "$CONF/tmux/colors.gen.tmux" <<EOF
# GENERATED by theme/apply.sh — do not edit (edit theme/palette.sh instead)
set -g status-style "bg=$TRON_BG,fg=$TRON_FG_DIM"
set -g status-left "#[fg=$TRON_BG,bg=$TRON_ACCENT,bold] #S #[default] "
set -g status-right "#[fg=$TRON_ACCENT]%H:%M #[fg=$TRON_FG_DIM]%d.%m "
set -g window-status-format " #I:#W "
set -g window-status-current-format "#[fg=$TRON_ACCENT,bold] #I:#W "
set -g pane-border-style "fg=$TRON_FG_DIM"
set -g pane-active-border-style "fg=$TRON_ACCENT"
set -g message-style "bg=$TRON_BG_ALT,fg=$TRON_ACCENT"
set -g mode-style "bg=$TRON_ACCENT,fg=$TRON_BG"
set -g clock-mode-colour "$TRON_ACCENT"
EOF
say "tmux   -> config/tmux/colors.gen.tmux"

# ----------------------------------------------------------------- fish ----
cat > "$CONF/fish/colors.gen.fish" <<EOF
# GENERATED by theme/apply.sh — do not edit (edit theme/palette.sh instead)
set -gx TRON_ACCENT "$TRON_ACCENT"
set -gx TRON_WARN "$TRON_WARN"
set -g fish_color_normal        C8D6E0
set -g fish_color_command       ${TRON_ACCENT#\#}
set -g fish_color_param         C8D6E0
set -g fish_color_quote         ${TRON_ACCENT_SOFT#\#}
set -g fish_color_error         ${TRON_WARN#\#}
set -g fish_color_comment       4A6070
set -g fish_color_autosuggestion 4A6070
set -g fish_color_operator      ${TRON_ACCENT_SOFT#\#}
set -g fish_color_end           ${TRON_ACCENT#\#}
set -g fish_color_redirection   ${TRON_ACCENT_SOFT#\#}
set -g fish_pager_color_prefix  ${TRON_ACCENT#\#}
set -g fish_pager_color_progress 4A6070
set -g fish_pager_color_completion C8D6E0
set -g fish_pager_color_description 4A6070
EOF
say "fish   -> config/fish/colors.gen.fish"

# ------------------------------------------------ rendered copies below ----
# starship: no include support -> copy (accent-swapped) to the default path
render_swapped "$CONF/starship.toml" "$XDG/starship.toml"
say "starship -> ~/.config/starship.toml (rendered copy)"

# fastfetch: jsonc has no includes -> render the whole dir
mkdir -p "$XDG/fastfetch"
render_swapped "$CONF/fastfetch/config.jsonc" "$XDG/fastfetch/config.jsonc"
cp "$CONF/fastfetch/logo.txt" "$XDG/fastfetch/logo.txt"
say "fastfetch -> ~/.config/fastfetch/ (rendered copy)"

# btop: rewrites its own config at runtime, so it must NOT be a symlink into
# the repo -> render copies. Theme file gets the accent swap.
mkdir -p "$XDG/btop/themes"
render_swapped "$CONF/btop/themes/tron.theme" "$XDG/btop/themes/tron.theme"
[ -f "$XDG/btop/btop.conf" ] || cp "$CONF/btop/btop.conf" "$XDG/btop/btop.conf"
say "btop -> ~/.config/btop/ (rendered copy; btop.conf only seeded once)"

# openbox theme: themerc lives in ~/.themes, not ~/.config -> render copy
mkdir -p "$HOME/.themes/TronGrid/openbox-3"
render_swapped "$CONF/openbox/themerc.in" "$HOME/.themes/TronGrid/openbox-3/themerc"
say "openbox theme -> ~/.themes/TronGrid/"

command -v eww >/dev/null && eww ping >/dev/null 2>&1 && eww reload >/dev/null 2>&1 || true

# ------------------------------------------------------------- wallpaper ----
if command -v magick >/dev/null 2>&1 || command -v convert >/dev/null 2>&1; then
    bash "$THEME_DIR/wallpapers/generate.sh" || echo "[theme] WARNING: wallpaper generation failed" >&2
else
    echo "[theme] WARNING: imagemagick not installed, skipping wallpaper generation" >&2
fi

say "done."
